### ISSUE TITLE
Build of the current master fails: `error: implicit declaration of function 'mbedtls_pk_load_file'; did you mean 'mbedtls_mpi_read_file'? [-Wimplicit-function-declaration]`

### ISSUE THREAD

**Issue by barracuda156** [h2o/picotls#537]
```
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-e4f0a27ebd1c07ebed68674258da9556fb92b46b/lib/mbedtls_sign.c: In function 'ptls_mbedtls_load_private_key':
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-e4f0a27ebd1c07ebed68674258da9556fb92b46b/lib/mbedtls_sign.c:619:16: error: implicit declaration of function 'mbedtls_pk_load_file'; did you mean 'mbedtls_mpi_read_file'? [-Wimplicit-function-declaration]
  619 |     if ((ret = mbedtls_pk_load_file(pem_fname, &buf, &n)) != 0) {
      |                ^~~~~~~~~~~~~~~~~~~~
      |                mbedtls_mpi_read_file
make[2]: *** [CMakeFiles/picotls-mbedtls.dir/lib/mbedtls_sign.c.o] Error 1
make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/build'
make[1]: *** [CMakeFiles/picotls-mbedtls.dir/all] Error 2
```

**Comment by barracuda156** [comment]
This is still broken in 9b88159ce763d680e4a13b6e8f3171ae923a535d

```
:info:build /opt/local/bin/ccache /opt/local/bin/gcc-mp-14  -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/deps/cifra/src/ext -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/deps/cifra/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/deps/micro-ecc -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/deps/picotest -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/include -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/build -I/opt/local/include -I/opt/local/libexec/openssl3/include -std=c99 -Wall -O2 -g  -pipe -I/opt/local/libexec/openssl3/include -Os -DNDEBUG -I/opt/local/libexec/openssl3/include -isystem/opt/local/include/LegacySupport -isystem/opt/local/include -DPICOTLS_USE_BROTLI=1 -DPTLS_HAVE_MBEDTLS=1 -arch ppc -mmacosx-version-min=10.6 -DPTLS_MEMORY_DEBUG=1 -MD -MT CMakeFiles/test-openssl.t.dir/deps/cifra/src/hmac.c.o -MF CMakeFiles/test-openssl.t.dir/deps/cifra/src/hmac.c.o.d -o CMakeFiles/test-openssl.t.dir/deps/cifra/src/hmac.c.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/deps/cifra/src/hmac.c
:info:build /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/lib/mbedtls_sign.c: In function 'ptls_mbedtls_load_private_key':
:info:build /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/picotls-9b88159ce763d680e4a13b6e8f3171ae923a535d/lib/mbedtls_sign.c:619:16: error: implicit declaration of function 'mbedtls_pk_load_file'; did you mean 'mbedtls_mpi_read_file'? [-Wimplicit-function-declaration]
:info:build   619 |     if ((ret = mbedtls_pk_load_file(pem_fname, &buf, &n)) != 0) {
:info:build       |                ^~~~~~~~~~~~~~~~~~~~
:info:build       |                mbedtls_mpi_read_file
:info:build make[2]: *** [CMakeFiles/picotls-mbedtls.dir/lib/mbedtls_sign.c.o] Error 1
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_picotls/picotls/work/build'
:info:build make[1]: *** [CMakeFiles/picotls-mbedtls.dir/all] Error 2
:info:build make[1]: *** Waiting for unfinished jobs....
```
